### ISSUE TITLE
tabspaces-switch-or-create not  creating new 'workspaces''

### ISSUE THREAD

**Issue by appleinario** [mclear-tools/tabspaces#17] opened 2022-09-24 15:10 UTC
I hope I'm not mistaken here but:

Testing out tabspaces-switch-or-create-workspace doesn't seem to create any new  'workspaces'. I took a look at tabspaces.el, and it is aliased to tab-bar-switch-to-tab. Using that function doesn't create new tabs too, and instead just tries to switch tabs despite no tabs existing. 

However, I do see a separate function tab-bar-new-tab / tab-bar-new-tab-to, which creates new tabs. Using the tabspaces-switch-or-create-workspace / tab-bar-switch-to-tab functions switches between the created new tabs.

Am I missing something here? Is the function supposed to work for both switch and creation of 'workspaces'? Thank you so much.

**Comment by mclearc** [comment] 2022-09-24 15:44
Thanks for this -- you're not missing something. This looks like a regression. I'll have it fixed in a bit.

**Closed** 2022-09-24 18:07 UTC

**Comment by ParetoOptimalDev** [comment] 2022-11-27 23:36
Ah, this was why when I tested #18 I had weird behavior. When NixOS updates or I update packages I'll test it again.

**Comment by ChauhanT** [comment] 2023-03-05 17:47
Hi, I also cannot switch, and get the following message:
```
tabspaces-switch-or-create-workspace: Symbol’s function definition is void: tab-switch
```

When I export it in my `use-package` block by adding it to `:commands`, the error changes to:
```
tabspaces-switch-or-create-workspace: Autoloading file /home/tc/.emacs.noevil/straight/build/tabspaces/tabspaces.elc failed to define function tab-switch
```

Hope this helps triangulate the issue!

**Comment by mclearc** [comment] 2023-03-05 22:58
> ```
> tabspaces-switch-or-create-workspace: Symbol’s function definition is void: tab-switch
> ```

`tab-switch` is an alias in tab-bar.el, which is required by tabspaces. So there is probably a problem with the way tab-bar is being loaded in your config. Maybe try reproducing with `emacs -q`? If you continue to see the error please open a new issue, as the problem being described in this current issue has been resolved. 

>     * Other info: I'm on emacs 27.1 on a Debian 11 box.

I wonder if the version of tab-bar in emacs 27 doesn't have the alias defined (I'm on emacs 29). Do you see the following in tab-bar.el?

```elisp
(defalias 'tab-switch          'tab-bar-switch-to-tab)
```

>     * I am the developer of Emacs Groundup, and want to move the distro to project.el and tab-bar for v0.2 - tabspaces has been a fantastic find ! I love the intuitive and simple interface. Thank you for sharing your work with the community 👏

I'm very glad you've found it useful!

**Comment by mclearc** [comment] 2023-03-07 02:00
Hmm -- is `tab-bar-switch-to-tab` defined? If so then just create the alias as above and load that before you load tabspaces.el and hopefully things should work. If `tab-bar-switch-to-tab` isn't present then I'll have to look more closely at the older version of tab-bar.el.

**Comment by ChauhanT** [comment] 2023-03-07 02:15
That did the trick! The function was indeed defined, and only the alias was missing. Thank you!!

**Comment by mclearc** [comment] 2023-03-07 02:21
Great! Let me know if you run into further issues.
